
Thread #x was created
   at 0x........: clone (in /...libc...)
   by 0x........: do_clone (in /lib/libpthread...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (rwlock_race.c:48)

Thread #x was created
   at 0x........: clone (in /...libc...)
   by 0x........: do_clone (in /lib/libpthread...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (rwlock_race.c:47)

Possible data race during write of size 4 at 0x........ by thread #x
   at 0x........: thread_func (rwlock_race.c:29)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: start_thread (in /lib/libpthread...)
   by 0x........: clone (in /...libc...)
 This conflicts with a previous write of size 4 by thread #x
   at 0x........: thread_func (rwlock_race.c:29)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: start_thread (in /lib/libpthread...)
   by 0x........: clone (in /...libc...)
 Location 0x........ is 0 bytes inside local var "s_racy"
 declared at rwlock_race.c:18, in frame #0 of thread x
Result: 2

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
